---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: raspbian
    image: ${SYNC_SERVER_IMAGE:-"balenalib/raspberrypi4-64-debian-python:buster"}
provisioner:
  name: ansible
  inventory:
    host_vars:
      raspbian:
        fail_on_service_errors: false
verifier:
  name: ansible
