---
- name: Converge
  hosts: all
  become: true
  vars:
    fail_on_service_errors: false
  tasks:
    - name: "Include bassinator.clusterhat"
      ansible.builtin.include_role:
        name: "bassinator.clusterhat"
