---
dependency:
  name: galaxy
driver:
  name: delegated
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
#  - name: raspbian
#    image: ${SYNC_SERVER_IMAGE:-"balenalib/raspberrypi4-64-debian-python:buster"}
  - name: cbridge
    groups:
      - raspberries
provisioner:
  name: ansible
  inventory:
    host_vars:
      cbridge:
        raw_hostname: '0x0031ce19'
        hostname: cbridge
        ansible_host: "{{ hostname }}.local"
        ansible_user: pi
        ansible_ssh_pass: raspberry
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
        ansible_python_interpreter: /usr/bin/python3
scenario:
  name: int
  converge_sequence:
    - converge
verifier:
  name: ansible
