---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  become: true
  gather_facts: false
  tasks:

  - name: Turn all nodes on
    ansible.builtin.command: clusterctrl on
    changed_when: true

  - name: Get clusterctrl status
    ansible.builtin.command: clusterctrl status
    register: ctrl_state
    changed_when: false

  - name: Check all nodes on
    ansible.builtin.assert:
      that:
        - '"p1:1" in ctrl_state.stdout_lines'
        - '"p2:1" in ctrl_state.stdout_lines'
        - '"p3:1" in ctrl_state.stdout_lines'
        - '"p4:1" in ctrl_state.stdout_lines'
      success_msg: "all nodes on"

  - name: Turn all nodes off
    ansible.builtin.command: clusterctrl off
    changed_when: true

  - name: Get clusterctrl status
    ansible.builtin.command: clusterctrl status
    register: ctrl_state
    changed_when: false

  - name: Check all nodes down
    ansible.builtin.assert:
      that:
        - '"p1:0" in ctrl_state.stdout_lines'
        - '"p2:0" in ctrl_state.stdout_lines'
        - '"p3:0" in ctrl_state.stdout_lines'
        - '"p4:0" in ctrl_state.stdout_lines'
      success_msg: "all nodes off"
